name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    #paths:
      #- "azure-vote/"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: ACR build
      run: |
       az login --service-principal -u ${{ secrets.SPID }} -p ${{ secrets.SPPass }} -t ${{ secrets.TenantID }}
       az acr build -r markitoacreastus -t vote-app:{{.Run.ID}} azure-vote/
       
